name: Publish
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
permissions:
    contents: write
    packages: write
    pull-requests: write
jobs:
    Publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "npm"
            - run: npm ci
            - name: Create PR/Publish
              id: changesets
              uses: changesets/action@v1
              with:
                publish: npm run release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
